version: '3.8'

services:
  nginx-service:
    image: nginx
    container_name: nginx
    ports:
      - "5003:6001"
      - "5001:6002"
      - "8003:8003"
      - "8002:8002"
      - "8001:8001"
      - "8004:8004"
      - "8005:8005"
    depends_on:
      - payment-service1
      - payment-service2
      - order-service1
      - order-service2
      - product-service1
      - product-service2
    networks:
      - ordering-system-network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      
  product-service1:
    build:
      context: ./ProductService
      dockerfile: Dockerfile
    image: product-service
    container_name: product-service-api1
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=ordering-system-mssql;Database=ProductService;User Id=sa;Password=Mahmudur123;TrustServerCertificate=True;
      - Services__UserService=http://nginx:8004
      - Services__ObjectStoreService=http://nginx:8005
      - Services__RedisService=ordering-system-redis:6379,password=Mahmudur123
    depends_on:
      - sqlserver
      - redis
    networks:
      - ordering-system-network
    volumes:
      - ./logs:/app/logs
      
  product-service2:
    build:
      context: ./ProductService
      dockerfile: Dockerfile
    image: product-service
    container_name: product-service-api2
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=ordering-system-mssql;Database=ProductService;User Id=sa;Password=Mahmudur123;TrustServerCertificate=True;
      - Services__UserService=http://nginx:8004
      - Services__ObjectStoreService=http://nginx:8005
      - Services__RedisService=ordering-system-redis:6379,password=Mahmudur123
    depends_on:
      - sqlserver
      - redis
    networks:
      - ordering-system-network
    volumes:
      - ./logs:/app/logs    
      
  order-service1:
    build:
      context: ./OrderService
      dockerfile: Dockerfile
    image: order-service
    container_name: order-service-api1
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=ordering-system-mssql;Database=OrderService;User Id=sa;Password=Mahmudur123;TrustServerCertificate=True;
      - Services__ProductService=http://nginx:6002
      - Services__PaymentService=http://nginx:6001
      - Services__UserService=http://nginx:8004
    depends_on:
      - product-service1
      - product-service2
      - user-service1
      - user-service2
    networks:
      - ordering-system-network
    volumes:
      - ./logs:/app/logs
  order-service2:
    build:
      context: ./OrderService
      dockerfile: Dockerfile
    image: order-service
    container_name: order-service-api2
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=ordering-system-mssql;Database=OrderService;User Id=sa;Password=Mahmudur123;TrustServerCertificate=True;
      - Services__ProductService=http://nginx:6002
      - Services__PaymentService=http://nginx:6001
      - Services__UserService=http://nginx:8004
    depends_on:
      - product-service1
      - product-service2
      - user-service1
      - user-service2
    networks:
      - ordering-system-network
    volumes:
      - ./logs:/app/logs
  
  payment-service1:
    build:
      context: ./PaymentService
      dockerfile: Dockerfile
    image: payment-service
    container_name: payment-service-api1
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=ordering-system-mssql;Database=PaymentService;User Id=sa;Password=Mahmudur123;TrustServerCertificate=True;
      - Services__UserService=http://nginx:8004
    depends_on:
      - user-service1
      - user-service2
    networks:
      - ordering-system-network
    volumes:
      - ./logs:/app/logs
  
  payment-service2:
    build:
      context: ./PaymentService
      dockerfile: Dockerfile
    image: payment-service
    container_name: payment-service-api2
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=ordering-system-mssql;Database=PaymentService;User Id=sa;Password=Mahmudur123;TrustServerCertificate=True;
      - Services__UserService=http://nginx:8004
    depends_on:
      - user-service1
      - user-service2
    networks:
      - ordering-system-network
    volumes:
      - ./logs:/app/logs
      
  user-service1:
    build:
      context: ./UserService
      dockerfile: Dockerfile
    image: user-service
    container_name: user-service-api1
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=ordering-system-mssql;Database=UserService;User Id=sa;Password=Mahmudur123;TrustServerCertificate=True;
    depends_on:
      - sqlserver
      - redis
    networks:
      - ordering-system-network
    volumes:
      - ./logs:/app/logs
      
  user-service2:
    build:
      context: ./UserService
      dockerfile: Dockerfile
    image: user-service
    container_name: user-service-api2
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=ordering-system-mssql;Database=UserService;User Id=sa;Password=Mahmudur123;TrustServerCertificate=True;
    depends_on:
      - sqlserver
      - redis
    networks:
      - ordering-system-network
    volumes:
      - ./logs:/app/logs    
      
  object-store-service1:
    build:
      context: ./ObjectStoreService
      dockerfile: Dockerfile
    image: object-store-service
    container_name: object-store-service-api1
    volumes:
      - ./wwwroot:/app/wwwroot
      - ./logs:/app/logs
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=ordering-system-mssql;Database=ObjectStoreService;User Id=sa;Password=Mahmudur123;TrustServerCertificate=True;
    depends_on:
      - sqlserver
    networks:
      - ordering-system-network
      
  object-store-service2:
    build:
      context: ./ObjectStoreService
      dockerfile: Dockerfile
    image: object-store-service
    container_name: object-store-service-api2
    volumes:
      - ./wwwroot:/app/wwwroot
      - ./logs:/app/logs
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=ordering-system-mssql;Database=ObjectStoreService;User Id=sa;Password=Mahmudur123;TrustServerCertificate=True;
    depends_on:
      - sqlserver
    networks:
      - ordering-system-network    
      
  redis:
    image: redis
    container_name: ordering-system-redis
    ports:
      - "6380:6379"
    command: redis-server --requirepass Mahmudur123  
    networks:
      - ordering-system-network  
      
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ordering-system-mssql
    ports:
      - "1435:1433"
    environment:
      SA_PASSWORD: "Mahmudur123"
      ACCEPT_EULA: "Y"
    networks:
      - ordering-system-network
      
  promtail:
    image: grafana/promtail:latest
    container_name: ordering-system-promtail
    volumes:
      - ./logs:/app/logs
      - ./promtail-config.yaml:/etc/promtail/promtail-config.yaml
    command: -config.file=/etc/promtail/promtail-config.yaml
    networks:
      - ordering-system-network
      
  prometheus:
    image: prom/prometheus
    container_name: ordering-system-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - product-service1
      - product-service2
    networks:
      - ordering-system-network
      
  loki:
    image: grafana/loki:2.9.1
    container_name: ordering-system-loki
    ports:
      - "3100:3100"
    networks:
      - ordering-system-network
      
  grafana:
    image: grafana/grafana
    container_name: ordering-system-grafana
    ports:
      - "3000:3000"
    depends_on:
      - loki
      - prometheus
    networks:
      - ordering-system-network

networks:
  ordering-system-network:
