version: '3.8'

services:
  product-service:
    build:
      context: ./ProductService
      dockerfile: Dockerfile
    image: product-service
    container_name: product-service-api
    ports:
      - "8001:8000"
      - "5001:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=ordering-system-mssql;Database=ProductService;User Id=sa;Password=Mahmudur123;TrustServerCertificate=True;
      - Services__UserService=http://user-service-api:8000
      - Services__ObjectStoreService=http://object-store-service-api:8000
      - Services__RedisService=ordering-system-redis:6379,password=Mahmudur123
    depends_on:
      - sqlserver
      - redis
    networks:
      - ordering-system-network
    volumes:
      - ./logs:/app/logs
      
  order-service:
    build:
      context: ./OrderService
      dockerfile: Dockerfile
    image: order-service
    container_name: order-service-api
    ports:
      - "8002:8000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=ordering-system-mssql;Database=OrderService;User Id=sa;Password=Mahmudur123;TrustServerCertificate=True;
      - Services__ProductService=http://product-service-api:5000
      - Services__PaymentService=http://payment-service-api:5000
      - Services__UserService=http://user-service-api:8000
    depends_on:
      - product-service
      - user-service
      - payment-service
    networks:
      - ordering-system-network
  
  payment-service:
    build:
      context: ./PaymentService
      dockerfile: Dockerfile
    image: payment-service
    container_name: payment-service-api
    ports:
      - "8003:8000"
      - "5003:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=ordering-system-mssql;Database=PaymentService;User Id=sa;Password=Mahmudur123;TrustServerCertificate=True;
      - Services__UserService=http://user-service-api:8000
    depends_on:
      - user-service
    networks:
      - ordering-system-network
      
  user-service:
    build:
      context: ./UserService
      dockerfile: Dockerfile
    image: user-service
    container_name: user-service-api
    ports:
      - "8004:8000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=ordering-system-mssql;Database=UserService;User Id=sa;Password=Mahmudur123;TrustServerCertificate=True;
    depends_on:
      - sqlserver
      - redis
    networks:
      - ordering-system-network
      
  object-store-service:
    build:
      context: ./ObjectStoreService
      dockerfile: Dockerfile
    image: object-store-service
    container_name: object-store-service-api
    volumes:
      - ./wwwroot:/app/wwwroot
    ports:
      - "8005:8000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=ordering-system-mssql;Database=ObjectStoreService;User Id=sa;Password=Mahmudur123;TrustServerCertificate=True;
    depends_on:
      - sqlserver
    networks:
      - ordering-system-network
      
  redis:
    image: redis
    container_name: ordering-system-redis
    ports:
      - "6380:6379"
    command: redis-server --requirepass Mahmudur123  
    networks:
      - ordering-system-network  
      
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ordering-system-mssql
    ports:
      - "1435:1433"
    environment:
      SA_PASSWORD: "Mahmudur123"
      ACCEPT_EULA: "Y"
    networks:
      - ordering-system-network
      
  promtail:
    image: grafana/promtail:latest
    container_name: ordering-system-promtail
    volumes:
      - ./logs:/app/logs
      - ./promtail-config.yaml:/etc/promtail/promtail-config.yaml
    command: -config.file=/etc/promtail/promtail-config.yaml
    networks:
      - ordering-system-network
      
  prometheus:
    image: prom/prometheus
    container_name: ordering-system-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - product-service
    networks:
      - ordering-system-network
      
  loki:
    image: grafana/loki:2.9.1
    container_name: ordering-system-loki
    ports:
      - "3100:3100"
    networks:
      - ordering-system-network
      
  grafana:
    image: grafana/grafana
    container_name: ordering-system-grafana
    ports:
      - "3000:3000"
    depends_on:
      - loki
      - prometheus
    networks:
      - ordering-system-network

networks:
  ordering-system-network:
