events {}

http {

	# REST API upstreams

    upstream payment_api {
        server payment-service-api1:8000;
        server payment-service-api2:8000;
        keepalive 32;
    }
    
    upstream order_api {
        server order-service-api1:8000;
        server order-service-api2:8000;
        keepalive 32;
    }
    
    upstream product_api {
        server product-service-api1:8000;
        server product-service-api2:8000;
        keepalive 32;
    }
    
    upstream user_api {
        server user-service-api1:8000;
        server user-service-api2:8000;
        keepalive 32;
    }
    
    upstream object_store_api {
        server object-store-service-api1:8000;
        server object-store-service-api2:8000;
        keepalive 32;
    }


    # gRPC upstreams

    upstream payment_grpc {
        server payment-service-api1:5000;
        server payment-service-api2:5000;
        keepalive 100;
    }
    
    upstream product_grpc {
        server product-service-api1:5000;
        server product-service-api2:5000;
        keepalive 100;
    }
    
	# Payment REST API
    
    server {

        listen 8003;

        location / {
            proxy_pass http://payment_api/;
            proxy_http_version 1.1;
            proxy_set_header   Connection "";
            proxy_set_header   Host $host;
        }

    }
    
    # Order REST API
    
    server {

        listen 8002;

        location / {
            proxy_pass http://order_api/;
            proxy_http_version 1.1;
            proxy_set_header   Connection "";
            proxy_set_header   Host $host;
        }

    }
    
    # Product REST API
    
    server {

        listen 8001;

        location / {
            proxy_pass http://product_api/;
            proxy_http_version 1.1;
            proxy_set_header   Connection "";
            proxy_set_header   Host $host;
        }

    }
    
    # User REST API
    
    server {

        listen 8004;

        location / {
            proxy_pass http://user_api/;
            proxy_http_version 1.1;
            proxy_set_header   Connection "";
            proxy_set_header   Host $host;
        }

    }
    
    # ObjectStore REST API
    
    server {

        listen 8005;

        location / {
            proxy_pass http://object_store_api/;
            proxy_http_version 1.1;
            proxy_set_header   Connection "";
            proxy_set_header   Host $host;
        }

    }

    # Payment gRPC

    server {

        listen 6001 http2;

        location / {
            grpc_pass grpc://payment_grpc;
        }

    }
    
    # Product gRPC
    
    server {

        listen 6002 http2;

        location / {
            grpc_pass grpc://product_grpc;
        }

    }
}
