events {}

http {

	# REST API upstreams

    upstream payment_api {
        server payment-service-api1:8000;
        server payment-service-api2:8000;
    }


    # -----------------------------
    # gRPC upstreams
    # -----------------------------

    upstream payment_grpc {
        server payment-service-api1:5000;
        server payment-service-api2:5000;
        keepalive 100;
    }
    
	# REST APIs
    
    server {

        listen 8003;

        location / {
            proxy_pass http://payment_api/;
        }

    }

    # gRPC server

    server {

        listen 6000 http2;

        location / {
            grpc_pass grpc://payment_grpc;
        }

    }
}
