global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "product-service-api"
    static_configs:
      - targets: ["product-service-api:8000"]
      
  - job_name: "order-service-api"
    static_configs:
      - targets: ["order-service-api:8000"]
      
  - job_name: "user-service-api"
    static_configs:
      - targets: ["user-service-api:8000"]
      
  - job_name: "payment-service-api"
    static_configs:
      - targets: ["payment-service-api:8000"]
