global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "product-service-api"
    static_configs:
      - targets: ["nginx:8001"]
      
  - job_name: "order-service-api"
    static_configs:
      - targets: ["nginx:8002"]
      
  - job_name: "user-service-api"
    static_configs:
      - targets: ["nginx:8004"]
      
  - job_name: "payment-service-api"
    static_configs:
      - targets: ["nginx:8003"]
      
  - job_name: "object-store-service-api"
    static_configs:
      - targets: ["nginx:8005"]
